### ISSUE TITLE
Definition for rule 'wc/define-tag-after-class-definition' was not found

### ISSUE THREAD

**Issue by RettentoRectangle** [43081j/eslint-plugin-wc#122]
I just tried to merge our ce and wc configs and I got this error.

**Definition for rule 'wc/define-tag-after-class-definition' was not found**

package.json

devDependency: {
  'eslint-plugin-wc': '^2.0.0'
}

**Comment by 43081j** [comment]
i think that's the one we decided to rename to `wc/guard-define` (part of why it was a breaking change).

we probably need a migration guide for people coming from the old custom elements plugin in that case

**Comment by 43081j** [comment]
Published 2.0.3 which should fix this now

thanks for reporting! good catch
