### ISSUE TITLE
file-name-matches-element is broken after migrating to v2

### ISSUE THREAD

**Issue by RettentoRectangle** [43081j/eslint-plugin-wc#126]
eslintrc:
wc/file-name-matches-element': [ 2, { transform: 'none' } ]

/components/BaseBucketHolder/BaseBucketHolder.tsx
14. export default abstract class BaseBucketHolder extends HTMLElement {
(no customElements.define because it's an abstract class)
14:31  error  File name should be "" but was "BaseBucketHolder"  wc/file-name-matches-element

/components/Bucket/Bucket.tsx
16. export default class Bucket extends HTMLElement {
...
110: customElements.define('sni-bucket', Bucket)
16:22  error  File name should be "" but was "Bucket"  wc/file-name-matches-element

And we got many-many more.

It worked well when we used ce-plugin.

edit:
(as I see you don't have tests for .ts(x) filenames, nor abstract classes which extends from HTMLElement without registering in customElements)

**Comment by 43081j** [comment]
interesting

it shouldn't be anything to do with the file extension. i'll take a look, thanks for reporting!

**Comment by RettentoRectangle** [comment]
Can you release a new version?
We'd like to test it. :)

**Comment by 43081j** [comment]
👍  i'll try get a new version out tomorrow

**Comment by RettentoRectangle** [comment]
Works like charm.
Thank you!
