### ISSUE TITLE
Classes leveraging mixins are not getting linted 

### ISSUE THREAD

**Issue by JamesIves** [43081j/eslint-plugin-wc#142]
When configuring the settings for the linting rules, if the class is extending from [something that uses a mixin](https://lit.dev/docs/composition/mixins/) it is not recognized and gets skipped.  For example I have the following in my `eslint.config.mjs` file:

```js
settings: {
   wc: {
     elementBaseClasses: [
       'LitElement',
       'MyBaseElement'
     ],
   },
 },
```

If I have a class that extends from `MyBaseElement` things are properly picked up as you'd expect and all of the `wc/*` configured rules do their thing. 

```ts
export default class MySwitch extends MyBaseElement {}
```

However if I use a mixin no linting rules work:

```ts
export default class MySwitch extends Localizable(MyBaseElement) {}
```

I'm not sure if there's some type of string I can place in settings to make this work, but so far the following I've tried doesn't seem to do the trick:

```js
settings: {
   wc: {
     elementBaseClasses: [
       'LitElement',
       'MyBaseElement',
       'Localizable',
       'Localizable(MyBaseElement)',
       'Localizable<MyBaseElement>'
     ],
   },
 },
```

**Comment by 43081j** [comment]
we could probably make this work, but I wonder if its more reliable to just document the class as an element

the linter will pick up the `@customElement` jsdoc tag like this:

```ts
/**
 * my element
 * @customElement my-element
 */
class MyElement extends Mixin1(Mixin2(LitElement)) {
}
```

**Comment by JamesIves** [comment]
Ah yeah that seems to work, I was using `@element`. Seems like there's multiple ways to define the same type of tag between `@element`, `@tagname`, `@tag` etc for the purpose of the custom elements manifest.

**Comment by 43081j** [comment]
in the web component analyzer, the lit analyzer, and CEM, we've generally used `@customElement`

e.g. [in lit analyzer](https://github.com/lit/lit/blob/267d243aeec13a6f0e8184420919db4c519b8caf/packages/labs/analyzer/src/lib/custom-elements/custom-elements.ts#L74-L76), and [in web-component-analyzer](https://github.com/runem/web-component-analyzer/blob/4a852d9a185ade2600f0598943759df46997d2c2/src/analyze/flavors/js-doc/discover-definitions.ts#L19) (though that checks both for legacy reasons)

**Comment by JamesIves** [comment]
Ah sad that the [@open-wc/analyzer](https://custom-elements-manifest.open-wc.org/analyzer/getting-started/#supported-jsdoc) project doesn't seem to support `@customElement` at all. Seems like a workaround in my situation would be to do this to trigger the linting rules:

/**
 * my element
 * @customElement
 * @tag my-element
 */
class MyElement extends Mixin1(Mixin2(LitElement)) {
}

Are you open to supporting a larger cross-section of these types of JSDoc tags? We leverage this  pretty heavily as we have a number of tooling derived from it.

**Comment by 43081j** [comment]
yeah custom elements manifest spec doesn't define which JSDoc tags to use, if I remember correctly

I'm surprised the analyser you're using (openwc) doesn't look for `customElement`, it really should.

@thepassle any idea why that might be? iirc you worked on that analyser right?

**Comment by 43081j** [comment]
I think so yeah. its not really a responsibility of the custom elements manifest, but analysers generally have to discover these elements in the first place - so that's where you would check it

i.e. finding that a class is a custom element in situations where you didn't see a `define` call

I think it makes sense to do what you suggest so all these tools are aligned

**Comment by thepassle** [comment]
Yeah that sounds fine by me

**Comment by JamesIves** [comment]
@thepassle Pull request: https://github.com/open-wc/custom-elements-manifest/pull/287

**Comment by JamesIves** [comment]
After all these changes this now works with `0.10.4` of `@custom-elements-manifest/analyzer`, thank you both!
