### ISSUE TITLE
require-listener-teardown not warning

### ISSUE THREAD

**Issue by the0neWhoKnocks** [43081j/eslint-plugin-wc#68]
I added the plugin, and tested all `recommended` and `best-practice` rules. The only rule that didn't behave as described was [require-listener-teardown](https://github.com/43081j/eslint-plugin-wc/blob/master/docs/rules/require-listener-teardown.md).

My config is pretty barebones, and I reset everything that didn't have to do with this plugin and still no dice.

**Comment by 43081j** [comment]
can you give more info on how you tested it and where it didn't work, that you expected it would?

**Comment by the0neWhoKnocks** [comment]
> can you give more info on how you tested it and where it didn't work, that you expected it would?

I tried it in Atom, and via CLI. The code I used was the example provided in your doc. 

- Is the rule working for you?
- Is a specific version of Node required for that rule?

**Comment by dannobytes** [comment]
I troubleshooted this a bit and noticed that a couple of rules listed on the current README have not been correctly added to the rules export here:
https://github.com/43081j/eslint-plugin-wc/blob/master/src/index.ts#L11-L19

It's missing `require-listener-teardown` and `no-constructor-params`. That's probably why this isn't working as intended.

I can try putting up a PR to help fix this.

**Comment by dannobytes** [comment]
Er, looks like I don't have permissions to push upstream or set up a new PR. @43081j I have a commit that fixes this. Any access to put up a PR?

**Comment by dannobytes** [comment]
Thanks @stramel for the clue. I'll try that route and see if I can get that up
